import type { ToolType } from '@/lib/live/DrawingTools';
import type { ToolType as EngineToolType } from '@/lib/tools/ToolsEngine';
import {
  CursorIcon,
  CrosshairIcon,
  TrendlineIcon,
  RayIcon,
  HLineIcon,
  VLineIcon,
  RectangleIcon,
  ChannelIcon,
  FibonacciIcon,
  TextIcon,
  ArrowIcon,
  BrushIcon,
  HighlighterIcon,
  MeasureIcon,
  LongPositionIcon,
  ShortPositionIcon,
} from '@/components/ui/Icons';

export const TOOL_ICONS: Partial<Record<ToolType, React.FC<{ size?: number; color?: string }>>> = {
  cursor: CursorIcon,
  crosshair: CrosshairIcon,
  trendline: TrendlineIcon,
  ray: RayIcon,
  hline: HLineIcon,
  vline: VLineIcon,
  rectangle: RectangleIcon,
  parallelChannel: ChannelIcon,
  fibonacciRetracement: FibonacciIcon,
  fibonacciExtension: FibonacciIcon,
  text: TextIcon,
  arrow: ArrowIcon,
  brush: BrushIcon,
  highlighter: HighlighterIcon,
  measure: MeasureIcon,
  longPosition: LongPositionIcon,
  shortPosition: ShortPositionIcon,
};

export const TOOL_TYPE_MAPPING: Partial<Record<ToolType, EngineToolType>> = {
  cursor: 'cursor',
  crosshair: 'crosshair',
  trendline: 'trendline',
  ray: 'ray',
  hline: 'horizontalLine',
  vline: 'verticalLine',
  rectangle: 'rectangle',
  parallelChannel: 'parallelChannel',
  fibonacciRetracement: 'fibRetracement',
  fibonacciExtension: 'fibExtension',
  arrow: 'arrow',
  brush: 'brush',
  highlighter: 'highlighter',
  measure: 'measure',
  longPosition: 'longPosition',
  shortPosition: 'shortPosition',
  text: 'text',
};
